### ISSUE TITLE
リポジトリの名前を変えたい

### ISSUE THREAD

**Issue by Tatmius** [HUITGroup/moderator-s-meeting#10]
## 目的
agendaというと、「会議で話す予定の項目」とか「予定表」みたいな意味になってしまい、未来の事(issue)と過去の事(議事録)が共存するリポジトリとは少しずれている気がするので、リポジトリの名前を変更したい。

## TaskList
- [ ] リポジトリのrename

## 参考
- https://eikaiwa.dmm.com/uknow/questions/4086/
- https://www.merriam-webster.com/dictionary/minute

## 検討事項

- agenda -> monthly-meeting
- agenda-core -> moderator's-meeting

みたいな名前にしたいと思いました。

**Comment by shoumoji** [comment]
賛成です、ミーティングの方が直感的に分かりやすいと思います。
