### ISSUE TITLE
入部フローを確立したい

### ISSUE THREAD

**Issue by shoumoji** [HUITGroup/moderator-s-meeting#11]
## WHAT
現状入部フローがないので確立しておきたい。

## WHY
Discordや部費の導入などで入部フローが複雑化するので、ある程度作っておきたい。

## 具体例(提案)

1. 入部希望
1. Discordにゲスト権限として参加
1. 部費を支払う **連絡、支払方法も決める** 
1. Discordの部員権限を渡す
1. 活動に参加できるようになる(入部)

部費の支払い連絡はゲスト参加者しか見えない、入部用チャンネルをDiscordに作って記載する、等。

## 参考
<img width="928" alt="スクリーンショット 2020-12-01 15 01 27" src="https://user-images.githubusercontent.com/18581236/100703075-2ae3d100-33e6-11eb-8a6c-2798cfdaa68b.png">

**Comment by Tatmius** [comment]
12/1or2の運営会議である程度決めたいのでagendaからagenda-coreにtransferしました。

**Comment by noriHanda** [comment]
「覗いてみる」を可能にしたい。
1ヶ月間お試し入会的な感じで、毎月1日にモデレータが本入会（部費支払い済み）名簿とDiscordメンバーとを照らし合わせて、部費を払っていない人をキック。

**Comment by takapiro99** [comment]
自己紹介とかしたいよね

**Comment by Tatmius** [comment]
1. まずDiscordに入ってもらう(ゲスト権限)
2. ゲスト自己紹介チャンネルで自己紹介をしてもらう
3. chatとボイチャは入れるからそれでお試し入部
4. 良ければgoogle formで入会&部費を払う
5. 自己紹介(ちゃんとしたの)
