### ISSUE TITLE
今週のお試しゲスト

### ISSUE THREAD

**Issue by noriHanda** [HUITGroup/moderator-s-meeting#12]
## 目的
今週誰がDiscordにお試しで来るのか共有したい。
Twitter、知り合いの知り合いなど、チャネルが色々ありすぎて今週新しく来る人が誰か把握する人が属人化されてしまっている。

## TaskList
- [ ] 〇日の活動行くかも！みたいに言ってもらったら、逐次ここにリプする。

### テンプレ＆例
- 今週金曜の活動に〇〇という方がお試し参加します。××で連絡いただきました。対応した自分が当日対応可です。
- 今週金曜の活動に〇〇という方がお試し参加するかもです。××で連絡いただきました。対応した自分が多分当日対応可です。
- 今週金曜の活動に〇〇という方がお試し参加するかもです。××で連絡いただきました。対応した自分がワンチャン当日対応できないので@□□対応お願いします🙇‍♂️🙇‍♀️。
- 今週金曜の活動に〇〇という方がお試し参加します。××経由です。対応した△△が当日対応可です。

## 留意事項
- 参加連絡を受けた人は極力参加するように。

## 検討事項
- HUITGroup/agenda の Issue とした方が良い？

**Comment by noriHanda** [comment]
今週金曜の活動に「しゅんぺい」という方がお試し参加します。Twitterで連絡いただきました。対応した自分が当日多分対応可です。

**Comment by noriHanda** [comment]
今週金曜の活動に「むらおかき」という方がお試し参加しそうです。Twitterで連絡いただきました。対応した自分が当日多分対応可です。

**Comment by noriHanda** [comment]
今週金曜の活動に「悠志」という方がお試し参加します。Twitterで連絡いただきました。対応した自分が当日多分対応可です。

**Comment by noriHanda** [comment]
12/11金曜の活動に「しゅんぺい」という方がお試し参加します。Twitterで連絡いただきました。対応した自分が当日多分対応可です。

**Comment by noriHanda** [comment]
今週金曜の活動に「かりんとう」という方がお試し参加するかもです。Twitterで連絡いただきました。  @Tatmius からの紹介ということですが、
![Uploading スクリーンショット 2020-12-01 14.53.36.png…]()
自分が当日多分対応可です。

**Comment by tanakarn98** [comment]
今週金曜の活動に「ななみつき」という方がお試し参加するかもです。Twitterで連絡いただきました。対応した自分が多分当日対応可です。

**Comment by takapiro99** [comment]
これは外向きにしなくてもよさそうだから
ディスコのチャンネルで共有がよさそう

**Comment by shoumoji** [comment]
discordでの共有に切り替えたためクローズ
