### ISSUE TITLE
Discordの #ようこそ！ チャンネルの整備

### ISSUE THREAD

**Issue by noriHanda** [HUITGroup/moderator-s-meeting#16]
## 目的
せっかく「#ようそこ！」があるのにHUITのDiscordがどう使われているかなどの説明がない。
説明があると初めて入った人が混乱せず活動に参加しやすくなるのでは。

## TaskList
- [ ] どういう項目が必要か決める
- [ ] それぞれの項目の詳細を決める

## 参考
https://setup-lab.net/discord-welcome/

## 留意事項
- このチャンネルはサークルの説明だけとするのか、ルールは別のチャンネルに書くのかも決める

## 検討事項
- ようこそ画面のカスタマイズ

**Comment by shoumoji** [comment]
新入部員からも指摘があったので、rulesチャンネルを整備して、各チャンネルの説明を入れました。
