### ISSUE TITLE
会員名簿を作りましょう

### ISSUE THREAD

**Issue by manattan** [HUITGroup/moderator-s-meeting#17]
## 目的
- 会費を徴収することになるので, 誰が払ったかの把握（当然）
- 団体の規模とかわかりやすいし, OBOGリストも付随させておけば引き継ぎの時便利そうだよね。引退したらOBOGリストに随時以降ということで。

## TaskList
- [ ] 日程決め
- [ ] 係を明確にする
- [ ] なんらかの方法で集める（googleform -> スプシ?）

## 留意事項
- 

## 検討事項
-

**Comment by shoumoji** [comment]
## 入会フォーム

google フォーに入力、スプレッドシートに保存する入部フロー(昨年作ったもの)を使う。

部費収集方法はpaypayに払い込み(銀行に出金可)。

**Comment by shoumoji** [comment]
担当者はたかぴろ。

2月中に継続者を集める。

3月中に口座作成と新入部員用のフォーム作成。

**Comment by shoumoji** [comment]
既に作成済みのためクローズ
