### ISSUE TITLE
定期開催イベントをまとめる, 実行

### ISSUE THREAD

**Issue by manattan** [HUITGroup/moderator-s-meeting#18]
## 目的
- 毎回グダグダ決めるのも嫌なので, ある程度形にしましょう.
- 新歓の時の説明にも効果あり
- ある程度実行委員も決めることができそう

## TaskList
- [ ] まず何をするか決めよう
    - 輪読会
    - ハッカソン
    - LT会
    - キャンプ
    - 勉強会
    - amongusなどの仲良くなるきっかけとなるもの!?
- [ ] 日程を決めよ
- [ ] 担当者とか募ろ（今のmodelator, 年齢重なってきている問題あるので, そこらへんも踏まえつつ）
- [ ] それぞれにちゃんとdocumentとか作って具体的にしよ
- [ ] そして, ちゃんとやろ（だいじ）

## 留意事項
-

## 検討事項
-

**Comment by shoumoji** [comment]
## 今までやってたこと
- 不定期開催(有志が行うもの)
  - Docker講習会
  - React講習会
  - VPN講習会
  - アルゴリズム講習会
  - LT with cookpad

## 既にやってること
- LT(夏・年末)
- 年末アドカレ

## 今後やりたいこと
- 技術書典
- 企業との活動
