### ISSUE TITLE
Discordでの権限周りと、それに伴うOBの扱いについて

### ISSUE THREAD

**Issue by shoumoji** [HUITGroup/moderator-s-meeting#9]
## What
Discordの権限についてもう少し細かく詰めたい。
- どんな権限が必要か
- OBをどういう扱いにするのか

等々。

## WHY
今後1つのサーバを権限で管理するため、誰が何をできるのか予め決めたい。
権限が細かくなるので、新入部員を受け入れる前に権限作成をしておき、どこかのタイミングで移行できるようにしたい。

## Discord 権限についての具体例 (提案)
- 運営
  - 部員+運営会議も見れる
- 部員
  - 部費支払済者
  - 運営会議以外のすべてのチャンネルの閲覧/書込権
  - ボイチャ参加権
- ゲスト
  - 部費未支払者
  - #general, #chatの閲覧権 **発言は不可**
  - **ボイチャ参加不可**
  - 「サークルで何かやってる」ことは分かるが、オンライン活動への参加はできないような権限
  - まずはここに入れておくと良さそう
- OB
  - 以下に詳細あり
  - 部員と同じ権限

## OBについて
現状OBはいてもらった方が確実に良い (技術アドバイスできる人が少ないため)  
活動に頻繁に参加していたOBは、OB権限として部員と同格の権限を**部費なしでも**渡すべきだと思う。   
部費導入をきっかけに疎遠になるのだけは避けたい。OBには今まで通り指摘等して欲しい。

## 技術的な話
Discord Botでこの辺は良い感じにできるはず。  
技術的な仕組みはGolangの公式Discordサーバとかを参考にすると良さそう。

**Comment by takapiro99** [comment]
運営、部員、ゲスト、OBの分け方良いと思います！

> OBはいてもらった方が確実に良い 

わかります

> Discord Botでこの辺は

手動でポチポチやるのかなと思っていたけど、botでもできるのかな？

> Golangの公式Discordサーバ

少し詳しくどういうオペレーションか教えてください。。。

**Comment by Tatmius** [comment]
どのチャンネルを見れるようにするかとかはdiscordのロールの設定で割と柔軟にできるので、それでいいかなと思ってます。

@shoumoji のを参考にしながら自分もテストでやってみたのがあるのでそれを書きます。

## ・ サーバーに入りたての人
![image](https://user-images.githubusercontent.com/37615246/100542951-a29fe780-3290-11eb-814b-033d8dfc7e79.png)

- HUITのDiscordサーバーに入ったばっかりの人
- HUITの情報やルールなどしか見れないし、基本的にチャンネルに投稿も出来ない。

## ・ゲスト
![image](https://user-images.githubusercontent.com/37615246/100542992-e5fa5600-3290-11eb-9acd-4f93be16100c.png)

- 部費を払っていない人
- オンラインでの活動には参加できない
- 特定のテキストチャンネルは見れるが発言は出来ない。
- 誰彼にもテキストチャンネルが見えるようにするのはなんか嫌やな、と思ったので上記の入りたての人と分けました。こうすればサーバーの招待リンクをポンと公開しとけるのかなと。

## ・メンバー
![image](https://user-images.githubusercontent.com/37615246/100543511-ed6f2e80-3293-11eb-95da-9af8d6e36000.png)
- 部費を払っている人
- moderator onlyのチャンネル以外はすべて見れる+投稿とメッセージの編集が出来る

## ・OB
![image](https://user-images.githubusercontent.com/37615246/100543758-599e6200-3295-11eb-9e77-47a5216bd315.png)
- 卒業時まで部費を払っていた人
- 部費を払っていなくても基本的にメンバーと同じ権限を持つ

## ・運営(moderator)
![image](https://user-images.githubusercontent.com/37615246/100543573-3f17b900-3294-11eb-9cf8-3b9ff9fe5dda.png)

- メンバーに加えてmoderator-onlyの画面が見える。

**Comment by shoumoji** [comment]
おー！　こんな感じを想定してました！仕事が早い

**Comment by Tatmius** [comment]
- ゲストはボイチャも入れるようにする。
- サーバーのロールの分け方はこんな感じ
- 他のサークルの人に関しては普段は特別な権限を与えることはしない(入るのならお金をもらう)。

**Comment by Tatmius** [comment]
- ゲストでもチャットで発言は出来るように。履歴は見れるようにする。
- ゲスト自己紹介チャンネルでゲストに簡単な自己紹介を書いてもらう。
- ちゃんとした自己紹介チャンネルはメンバー権限以上で見れる。
